// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9jXLcNpYw+iqY3q/K9myrZTuZ3IyqUvPJsuPoi3+0kpyp3ch3ApHobozYIAOAkjsp",
	"V913uG94n+QWzgFIkAR/ut2SYoe7VROrid+Dg4Pzf36fROkqSwUTWk0Ofp+oaMlWFP55eKnSJNfshOql",
	"+TtmKpI80zwVk4PJKcskU6YboYJQ25bMecJIRvVyNplOMplmTGrOYLwsOM75kpW9TROiU0JxnFQQvWRE",
	"rZVmqxl5k2pG9JJqQsWasA9caS4W2PSGJwm5ZCS9ZvJGcq2ZMCtgH+gqS9jkYLJ/TeV+ki72aZbNknQx",
	"mU70OjNflJZcLCYfPxa/pJf/ZpGefJxODrPsHH4LLdu0Jukc1kizLOERNV9hXpGvJgc/I3AVm0wnv+Y0",
	"TpievK/PO5182DPN966pFHRlYPWzm/eo6G5/+C83Cq7NTXmUCs2ENsukSfJ2Pjn4+ffJ/5JsPjmY/Md+",
	"ecL79nj3v+cJc50+TrvbnrKEan6NeGAaS/ZrziWLzULhUN83IFdb3wtx/ROViAUVnGDlBxrH3LSlyUml",
	"Se2UprWDeCGuuUzFiglNrqnk9DJh5Iqt965pkhuM4lJNCRdmXSwmcW6GITIXmq/YjJhzvGJrQkVMsAej",
	"0ZKscqUNOl0yfcOYIE+gwdO/fUWiJZU00kyq2aSx7RYUcmA4kek1j5k8y1g0/KwCcDSnUAUkLRG1Zyxo",
	"9nE6MbjWch3LCYlpVUDjyf/3//y/VRiQJBWLKVGaSk1uuF4SShKmNZMklUTkq0smpwC7KBWackFESm6W",
	"XDOV0YjNBt3C3yepYAMAdbyiC9YG7j4sPxYJF+2933983322Z5rqXIWJBX4zpIISxcUiqcLYkrmYXXME",
	"iaMeJ5Jl1BKJMwNi/OdpLgT+64WUqZxMJ+/ElUhvxGQ6MRQjYZrFwwlNdQf+nI2P3iIa38pVNT65ZTY+",
	"lOtufPI2UgX0T2mSI+aW16cK7udszgVThAL2xuQaepBcsZhcruG5qlLr6lUKX4x3gv+aM7wPlub74xrc",
	"5yL0FDTx26efMNn7T8R5BEkDYUNwq5Og6tZxR6q5+1dcacBfD21tY7NHrtlKDaA9tTMs7zqVkq576Sd2",
	"Q/zovmU7OfI3jbMOnKc5zjmTTEQsxCTZT4apwTueJemaxeTt0fGegVHCqdCEm1M0FNNcrzmNNLmk0ZV5",
	"qDrnDuGSv54ekqXO8tWKyvVA0pUkPhBVO9n6gdFEL9eT6eQ5W0gaszhAqjYmT9XVlnO0NvEmb20ToEzV",
	"BsVyDehyvTxKxZwvmnAy38wbN+eLJnrRXC/fygUV/Decohyl88K0dPs4hRHDBwYLMZAN4qrp9+70VUu3",
	"d6ev+rGsmLocbdq6wyAGtkMjsCZpuE8Wk9TvYSGdy5b7zIRhA2Mcck7zRE8O5jRRrM49Hs+JljmbEpVn",
	"WSo1maeSHMcnJEM6WZ+XK2LH9gB1maYJo6IBKbeKEBCeUcWAdp+yBVdaro8ki5nQnCYB0uZ9hBXSKGLK",
	"cBKEOsaKSSLtUCHRS6mbVMbNkU/sFxjWDUDMcZr5Wl+x6URd8ez81dlPTPL5uh/QZ1c8I+evzkhkVjU3",
	"IzNybTo3JyngOZ3kismW99h+2XDhH4NnoaOAZAo/mxOngrCEgYTBBbmEnxX7NTc0tgnrhK+4DjPWK/qB",
	"r/KV5YsNvc+YjJjQQP3nlpQq81jkWWwgZFkKmNNMNYwpOClGBU5ixYWZdnLwpNg8F5otmERBTbGERTqV",
	"ffToFb1kyZlrbDrmgIfnS8nUMk3ivgH8dbUexJmFbMuBuM8ktlyegU9i2ROAEwLwkhH2gUW5oR1cdJyX",
	"ap3vsDouzggy6nCmB3Hr49QcwjF2eFLneqYGO6lmi3XfaKdpkqS5PnPN6xSnGCdIctJURy8+GDIXoDA+",
	"QYU7xaAl0phL05XEXF0hqxJ44mRkpLpI55JVqMHkw7ff/Oubryd1gnBO5YJp4veDaYGlqEzk2IpiIGo6",
	"ffN1k4UocKpLW1Pfi0EW3Ks/GVepmWnFJ9PJ9Sq+mkwnv0bpzVPDX9EbQ1eoDCygdh7wtfUsLP2f9/CN",
	"lCyYYBJewW0OooLSPrgta1sdrUnodSoHrfNmySSDERGuXBHTt/JUbnJQQPgC+x0A8sqqQ/A/Kl+hM74w",
	"cuupIQMqdDPamhLpqUCJtD/C80wUXwgWVx67uUxXsKejw8CpZfwnJhXM2Dizk2P7rULzrvE3FhOkDggy",
	"rsplWe3C3DxguPUZOWPSdCRqmeYJaGWumTRbidKF4L8VoyknsRjuS5mHT5v3NkElGap0VnRNJDPjklx4",
	"I0ATNSOvU2lesHl6QJZaZ+pgf3/B9ezqWzXjqSFvq1xwvd43HIzkl7lOpdqP2TVL9hVf7PmYvE8zvgeL",
	"FUh/V/F/SKbSXEZMBfHriosAu/MjFzE86QRbWp1fATIncp2+ODsnbgIEK0LQO/QSmAYQXMyZxJbFSTMR",
	"ZykXGv6IEm44CJVfrrhWDl8MnGfkiAqRgooN3/14Ro4FOaIrlhxRxW4dlAZ6as+ALAzMFdM0ppr2vU9v",
	"AUavmaZAOayOoatH6+2ySruJKqT97YbB7g0hprxvFlW8TdqVb0Q3XvGNaAfoUwAPHYvR2nQkFrdPLApW",
	"Lqz16jybQWxg+3vzsckNjqTrHkiXOWskXJuRCjz+jWiF071Wz/efkmYZk4TKNBcxocTIvnuRZMD4HZ2d",
	"TskqjVnCYpIKcpVfMimYZorwFIBJMz7z+A01u34y61xCQG3yIeMoAZyxKBWxCnF80B8taQXNuKYJj7le",
	"Fxy8txAzzTyVK6pR7vzq6aQphk4n7IOWtMsOWNyzFlayvD81A6EZmFCNyMWUYy0NeNGa7GAMzJmBc5Zm",
	"OWqdLtfw6+HJMVFwYwzsob3ZuaFrfLXKNb1MWMAciIgU5CrPQapX7Juv95iI0pjF5OTF6/LfPx6d/ceT",
	"x2Y5M/LaSbVLRszLNCt4Tc4SkG6pjw9dDCtShcqRXK41C/L9hoWVb4LKl2MRI5LBmmSBE9gHCT6Qql9z",
	"mvA5ZzEYToIXNOcBYvfu+PkdnJO3CEUXIbvHO/gdoG62AdSXwZtwxdYEe3n7t+oarlRe5f4rD0UvArdr",
	"vXyTxB0ApkYKHTZXkGMz0tdiuykRimaZTK9psh8zwWmyP6c8McKqKgwRxS49s7JqgTvh89JZRDUpntc0",
	"fEftkE15bloCjqRGAi5gPuh2GfKKqqSgLsZ+Q4OLOdnUv2kz8qNIbwSJvIaSkUMAHYun5DkT3PzXQOh7",
	"yq26ehin4sYMWud8bPC2EMSBYqD2DZbHFzNNudVup4IRaq6cdscd5VICB6LNmTre1SD1qUfSanpYqvS5",
	"pELBTOe8zdvBtCOar1B1UWyK6KIvi5EvMuuyaKhTQkWql0xWTtswQHtmrDAnogy9aK7ih3xFBZGMxoBN",
	"th3heCcMX+egQy/TXNsVF8sLErT0Eq57/BJVR8FjMLufOVZmtihaIlGpQuOGKqB85s2KSZ7htP67Dqq5",
	"5rsuGVVBQYU8vJSczR8RbFGyDm7OB2rQTgcKiG5UJxCWGqhB3dBrpk3XBENOQyhXAKA8/87L0m/crsBo",
	"CkiZzsk5WLG+B9MLsUZLX59pvk+mE2iwsRW2tjo7Vu1XN3TtZ9+AWoVmEx+t4q/EOu5LEt5uHKWbTCfn",
	"J6/BBsWdodd9QBoIezYEsNkUbWiXCav/4WjKCZUKmp6tRQT/+MnwuaYF6uGPxYlMF5Ipc/jvjPhjfXUy",
	"Frmmr/NE8yxhb28EkwrWdc0j9pwZyYcrI1eYTsMO4oWQaZKsmND2PfX22/hW3W7rk+wN0dqmgGVriwLI",
	"rS2qyzllWaq4TuU6CHoD8dYPjfPxPxZn9X3CmHanAH+ETg1Pwzs7/ME/Qfxl6Dkims/5ou5pM8x095Lr",
	"QPc+57UfC+7/jEWS6S0837aY9Qets1A3CwO0Shf27RYj/1HDfF017sO7kOVqad5BsAGE2Lgu4/lp2DhM",
	"vE53YjG/E1t2LpNBMB7k6mEGC75WWe6u3OtUmFvc9GitgnOFzfp9qUvFVUpsp/51+qMHfem63ZubO0EU",
	"lql48SEzhCLMxcpUEFY0IMgMwRmaseM8AZUcXzE1uxBmk7YFV+SXvxL7/78ckD3ymotcM3VAfvnrL2Rl",
	"xf3He3/7+4zskR/SXDY+Pf3KfHpO1wZor1Ohl9UWT/a+emJaBD89eep1/idjV/XRv5ldiDP0iGExMQdJ",
	"dWoWsWcaHhQaCSNaoRryIZstZlMYhguyNEsuxmPXTK7ht0dm3l/2fjkgp1Qsyl6P9779BQD35Ck5fG3O",
	"/lty+BpbT385IKCIdY2fTJ88ta2VBhHnyVO9JCuAIfbZ/+WAnGmWlcvad31wMfUeZ+iVW93LtyVIDNP1",
	"rdflQrzAyAIDOfJ479vpk2/2nn5ljzR4/Y9ypdMVvhrHYp526brqrDKoAlGfH5MIBiL2gtkDCE7ZpDLF",
	"IFwgMoIWAKSKqi9f487jwpuLw9+rttBsuVY8ook33mjBGM2do7lzv+Quh4uuts8Whsz3rfe44W7f9AUP",
	"syo1XYXvDt/t9w6CcLwOv/7OIW5eejMqcrPk0RIUW9CTDHKvN9NANEqAjr4pZnFtiFOTFNqH8OiePmPY",
	"mYUDQz5O2z3sSwHfNimc1+GS1da1ncN9XffRotgr/MjNeXkALTY/CK+qftShV01hA4c/S3DprkUZBNzM",
	"q2jK7VPaiab+a4e6NEf5QMPkRzXsRNvU7WTf9NrrgSrKTm2APPKUo6WKCOHV6pIumYiZZHHrM3xqG7iH",
	"t3XcPpNBdZ7OTao0aeUw7Gef0bCaMPg5SoVgkVUaFYcd8vYEZv34eZgQ2c/k+Lmvj6zNEEYM7Pnaezpq",
	"+F7wesUsjlA70mbWbW1L31XCFyMq4LVUaAoAL1Sa8N9QZ104zDG54oIm02LN6Adruk0J01HbcdH4rUjW",
	"kwNwha+iZm1XUw+A7UfpK0WagHCDWb6TOpSKq6qUwtjROEMNrqPDnk1/KehyGtbk4pDDtuSN0yTjhaUQ",
	"L4syMzS2tmJ6mcbVK+XrN98JBto80F5GOpXrU6YGBw93rdgbuatZddYCCsfmHZRcr4+WLLpqI0jtbeu3",
	"t0qyuOtBItOFZEyaG4EOD1u+AXvBN6CUeOpz4oo+gfS3b3472t86Uo+JYANglljnojHfCeWkf1+BXuhv",
	"N8HD0AbKmbra+Gtob1esrr1Jue4mWFsNLpY5aUPRxt3NahI8zAIKRr3eHmnAO21TFqdEb2BvykX3MDem",
	"dQGr5vvIV4YTXGVu77XB69E8w6yiW90qG42MR+RYa52tPgXOW1/M5mIGX83WB8CzlBT4Hb6eW13F2rVo",
	"2VLbzeq5w83rW167V1TpM8ZE26PhvtcfCkA1ZT5oHwtp6/1LWidq2vwt/4Embiacz4yRDHnNWaoDlWv4",
	"UyygHYNe8TmL1lHCfkjTK4c4DgOesXkqfcPU4Vwz6f2NDU7ZZZr6LcofNsGMylIaUwfa1FfTOoy/wLZx",
	"vDU3gbOV2JO43jsQGOvq0XLwXXELtb1uxyiEBmkjRH6ITQhiTY4ArcuWGlRNntVfNiRJtVXXiUrtc2UV",
	"ge+hpfU0q5KnoBd/+a3qso+/q1G9fe8O+t5JDNKMWWPG6Hv/R/O9n06sUnDYCTqua3dO+yFnj+dMQ/Ko",
	"5+iF11SVo0qx37iN7UCzFHPTaMUF1eDfILNUIQI72tu1kmDoK9gquViAr0vHZZmb76C5V+jpBx1rjOhQ",
	"Z+Ua3D1INBY0FNynTKXJdQe4qUJ3XGgehjju0TUkVJHUNCYPRZ4khM+JSPGXR2az5kfz7DsNWMCQekcH",
	"7PYePOBMsmue5ur1Jgdtz9j1TdbWph1veeBgD0iTvN2N74f0xilO5wmPNDDW0m7MBwAa3WE3k+nkTer+",
	"Bft6zlrSWHWiXG1t7Sj3VoWjcPyvBD9d2icadYTk7VkZp96mj1oF/XzPK4NgkDQa0OQwfxwct3NT2zDL",
	"b88Gb+GnqjHAbSP8Zpsvz/miNf4lhm/1sdD9gqglffq3bw7o49ls9mgoaKqTdgAKLtuSZ0dLKhb3Q9nr",
	"awheecFuOqicYDeWriG9K6ibZKv0msXDiJsjDR0TuSbh2UQq2JCp2i9u+0kVrp0bIXbBTPap6aIsH8Zp",
	"VNfhVE4xV1ef0n/FVulQXic0Qj0iI8snxaB2dUNB243jquKbh8CuInWZkOufVFrh60hyzSOabJ3+K7RQ",
	"P7tY82s5eeirt6DQZ7fI0Dffj734nq+Ylzci7M1l0yFRsbaekVUtkZ9S5309uyoE+Hmf30/D4ZhGvJOw",
	"nCKHEAZqpILAFMTl+DGi3n4qbeig+3VGDjVJGDXUWLCysUv86bJhVVLq/l5b/cGElblYv8tkGudgLp1q",
	"zuR3cwnpZmOkOP4drG4y5CfgloO71NIwFX7aHy9vkoUCqvC43aeakXfKBVBaP9sVNfwhKT2nayBRzg3w",
	"ohAcZgYvv8PJnkyt7idbUsX+8t0JEzEXi4vJoxbNegVSu90jDD5sj1Vk8PZ4xdZP0Ob8ZHrF1k//gn88",
	"DW/oYxdRgUuhslQo1nsr6tiM3VAUhm1i9FMh3XvIh1CIrSA4OfjqY9PHodqi3R+oAK5hlW+YZMSmtprn",
	"SbK2AI9DDkENd4fKlO3Et4v7rPGetMONsnQzGZaz015kuVXWzlpwQEMwiFpc/N1C8PsWawjGJoSmV2kS",
	"Ouhz7x7RSPPr0qvDujNsqjpyzirB6POqDnJjNwUI3xu4DivGWKkMWJ5Q0ieJrt7FA24d5quRFsNhUHOZ",
	"D0EBc7bHLV42+NFZWFTN2b8WOmCkwhOqNZNCdSVpQzVGZltWNtOgtuju7daRC44KkSnmsE4l/DfNNVH5",
	"fM4/TAlmdVqyJNlTep0wskjSSzcZrB9mpwvKhdIuYDVZkySlMcMpYE0r+uEVEwu9nBw8/ds304kdYnIw",
	"+b9/frz3d7r32+He/xxcXOz9a3YB//fzxcX7v1xc7F1c/PXi4h/v//Ph/x7W7tE/Hl5czH7GhqHP/6s9",
	"LVdXPl5UNZ6kCY8Gcq7vvB6Iru3vR7dPSdOLJGyoUV4qYEs8ie27omAG5wm6e0Y6p0kZV/yptNZK1D7J",
	"LW1EG9CXpn9u4I7RppfhxqPXvDSHR6YXZwBwRD9a57Fp4BgM26YhhdOW0ej+ezOIYJculOBTYa3VW3ke",
	"OGeJ3ViYycM3b89fHKAVoAjr4IqIVBPJdC5FJZPDo4EmaSNSLdK9f6tU7PGFSKUVzM3inUFsKwPlhi9U",
	"0afyRm0q8W5sHGhgNpJ7F3szYICyfUH34k1IXtziW+Jdscqqqld6Er7hPhh9PC7uA5xNud4Sav6xd3Cm",
	"W7tte5i+pDK+oZKBZRHjxwwnj3slFVvf7t257RpcqoZdOHQHQLOdlX6jlOth36C3EK8bzq7ue1ucpEaS",
	"id/O5xXnocMbyjWEZVuPZozZB1X9Cc3Vhgb8yoa8pTW+easNfK2qXiqfmh4klc+VbQa+110KKh9DwAg0",
	"q8OnPM4KSRkWzvc2c27geBu81FTsQ5aqktbTBRN6diFe0GgJCYeiVEqQkWNMQVIy8HgtrFU/ohm95AnX",
	"69mF6A8MxE1UblWUJgkWzCms0q2MkVlkq7uDeQsPF1CcB5uE09J3Jq2FMfzEtZLZyFQLp0bYYjmyQZ2Q",
	"s/+zNNXk+PkmQ2Hc5ZDnoxHqad5LRwQR2uFdvi0o5ZmjlAOXV7d/+wAtoNBcxbR6fO10q8HD93i+Z9AS",
	"DCIrKuii1ONYXwUoyhQleWy+3CyZcL87Z5ZLRuL0Rlj5ybwjNhlSwNnWtjvDsOtepgY3U7QuHvdt+3/s",
	"AVu8lVkO17RTBzb/ebQZ5nf4PFY2u93z2BxiAxe2EmCF/1p2nj6nkIHrba7fzu2/Pb/FbewRlUV6UwS+",
	"+rMGO9ccKKtfGyYHX8zrYcucStOFFoHJrhAm4MLNGfoRlFWpwPLeKfuWmNz22A3ICVUkh/+98RYdkkvJ",
	"6JW50Z07uVyTC39dF5OmM2aJXKrO0/4BFm/X1L1wnWqatJjlzCcvcjY008AcXZb6/ZGgY6WXLujUQ7gA",
	"VNMAstbPv7bhIDXi6qo3xcnGWUWmf7C0KMEHPCrT7tgB4O3m6grzXW5S2DPmEgxN66Kyp9M8W08Jb8zu",
	"vXTUmXzOlcxh1md5bAMDa8rDWotq7RB2zRJb4Cq9YbFZlm2NZFJi2ijCAU8zmzuqCYaFTPPs2bpdOYjG",
	"tyu2BubdBmQR6AZ1TMvqF27+S1huRVvm6Ysf/ny49z9077fHe39///Ne8e9/7c/e//XRP7yPAzS9oJh+",
	"J+g15daFI1jABivJeFTHnREpehaX2pXaRPCB7rujEA18PeyZvlY/Z05y0Zy3OMeN5g/ycLmfOtEVNHms",
	"msVMvMUVeZHdOorUAhierFMS2dqGWH606FAyvi7fLHguUgKp0vi1jRxi5vbYsS/XhKKaMRdcz0iZtKf4",
	"EXKDHpBfFOa/UZjZeUp+WeEPmNLG/LDEHyB5D6C3h2r/OPj5yd7f319cxH999I+Li/hntVqG8eqFiFLD",
	"1A+Jj2W2LdI5CG8GwkA1rTm++1xdllBuxFrMnzw4dR5OdWI7u7+f2UE++hn0ymRl9bpirsWe1d32ccbl",
	"mGe2Q7NKWGPM0IvUSO/XhG2jSUeFEptlF4rfQLdO08cYzjBm6/kTZutpXKjNEvc0u++2GElLNtCQwNDa",
	"tMzAHNYYFITCs96RkmS1J2mgLq1oR67vmyXTSyb91NZkSRW5ZEwQN0C4MCD6PH1C3fBDl8gdRwJ1apYl",
	"67JSa0sqtMbh2X1udEKerDVInGg/6iYf3zNp34l7tvNPPfvDFsdv4E2othme/NO/oapy8MNiyF2PZ23p",
	"papZqkzbAeKTN+rU31JACplueARbODAEAF8c0CyIa+FgxmCzalxjo8nIEtx7hGPwTAa5UDQZxzHs8Ust",
	"ORRmWPppAHiccnQ1LRoi9Wm0faBcEBO49QRiKlRLFEmowI1fq0NhvnD/XQk84lUvseGJE6cT0Kaf9iU+",
	"O4fnqDP5GaCsze00+7dKBXmYWqNuh/v3TrkVV6HBuRDdcFue3TIwXBVOR0smiLlD3gPCVYi9auFwzHkO",
	"Q7YWK1dLw81ewUGPUsn+bsVMeU5wfXVhfFxuFoeZbVzypVnghH0Czd9ZEZem+qLjdG2TLgZzmd5YBZgh",
	"wXDrweOWku8TvlhqcmRIcpr4yOrlYWmW1S8TpG+siTnMNVRm9hQwOd9zr1D42N+dvnKn8+64vIVgRCe5",
	"QlfmTLpX7L9OiUER4D4SLq4wAzXM597ODoeDbVVMbZqmGrzKCVphMAglAI79aAHV/CvlmuwbX0vL7yMN",
	"FtPdAjVw6D3vSu6FszIeQUOvaMVzqmm5TP+ag1YSSD91SzfjkzlPMHP/+auz8MXHxVyxdecifmTrjSa/",
	"Yuu+ueuXvQUqzSUOOvjhJGEAZXDpNc21SLc8dG9fBqlSyXUryMu2h65pO/R9LqUYmVSqLbZd4FBILXLC",
	"5hUG4hHHkqnC+6N34+ShY2qXqdJGtj3IUqkHBEl3AKhYbPDkDfcbOOZrFEY9HbP1I2DX6BhONUkj8AIv",
	"auOh01uAmIcj4+riOxS9AzMGwgJJsOSLBfBrIEeYydG0gvIK8EYQxcjm/ANaTRgHzZMZ7oA8BLMHONCY",
	"H9Qjbwb7leY6XUFFPRe0Eub0RsF414JxXMbmd76CZkQXxw8O/teQcAK1vsN0w0U5+1Ek3rlI3FL77hDv",
	"XZmmtSaA1rPEGjhmtk7dDq0B7VXq1DKVekpWNFpywcp12uMH+lPNE1KrZ4fkyDNfOteQI6za6dWvOrJ1",
	"OYvEi+7Du8KXv/pLo6HLmlL7xR+zGXDY8nOtx9HJu0b4/NHJu3rA/dHJuzfmaS8bvYZ8BI2++HO9O/5a",
	"G+E5V1eN/ubHem/zW62vF+tU9TH3PjRc071v9XQDz7myrIqfGjPgpF7zGa//XGT68T7URj2CiHnd8DC0",
	"vzd9C4sOQa/C4jw3qiLnZOMaNrTkperO6NRRXs38ciyu7W/H9pE6p+qqmNj/8YTJFRUQYendgZaScu7n",
	"Y0GrHyy1j8sm5UVrlo8rl+dXkytvsf/rmaay+Wux1MoA1hmk/vszqqPlc64yTNdU+2qhxhIH90ZXf1y/",
	"QN6RueDaO7FBNfcasCs/BcvwmR+5WDQIVKVEX/3HojV6p58ypVPZkhkHew7iCs6wqVfys93RzmMg32Jl",
	"TaQnU2JpjU/JC1Lj6ND7fptSt2a3yrQEiodOi6KjuKmpZZxb2XYvtVGAe9+znkaRKzE7NQ9bDu98XOYQ",
	"sfz8OgOpq5LhCEO0s8yGundSh049bXfOvR7CssHI9fRybTmhesIaWzJIdV7ElhHbe3SM6lGGocOWXcLj",
	"brTQnjXW6NOAAas9wqNaAjFgNGwZHsUR5wHD2KblOIGXqbWsZr1leJTmUzZgwEancuyuZ63VWbm1iz9u",
	"5Q3pxpRg4+ZYveuqNPOkOxclDRXoD/xUYh+nAyuttg4+KKq55foP691N6rYZo07U+mu+tiHnJj1bsXBo",
	"zc0gevR37sXWviE6rvgmXTfbdCf13KRzCzHfeIhPWkSYXH98v1GOP+BBWvxU3Keab8o1aE5Gh5R7d0gp",
	"DmKYFwqokEfPky/W88QTtIICVrEKVJnBNYNsb0aibCrLapYd17nfQLDhPD0Gk2Le0J6/54lTubTtGT6i",
	"A8Och6pRRF39IdCBaPZBk4fvzr/f+xYMExj2UNqmykkghs5OE3I/MO1c3EO/VdkL4whGx5jtt5e7M1+L",
	"AnctwVItubt5wh4ojIuaeqEw1mQDETEubbLIV0zyiBw/n5HnGKEDhPdiItNUX0zCtySNWefUGZNWB0pM",
	"2xn57zQH4oGLwVD8lbnqc7riCaeSpJGmifNlSBiFqJbfmExdisXH33z9NRwfRTeriK9sByyCF+rz9dPH",
	"jwz10jmP9xXTC/MfzaOrNbm0gT2kqLIzI8dzyBhUQGyKkfjVzcAVMPtUJPYAZpYXLniaq9Yk6wgtyAl8",
	"CwfVhnNvnf7fL5cTFWo4m/vYy4AzLECoMrSn1fN/Pi3GrvzsxJj3doWbhYr6ZKSXA/PvXF/jw0tIhs5O",
	"KDi6/N4MqCyoQktoJTB8gbttg8l9wy/zs5SO/NkYQzTGEJUy02ZxQ9hlt7FCMGZY0io+VSUtrC4x3uR7",
	"l7TKgxgkaSHNHiWtL1XS6lfjNMKWL6GwSpCHg0/AhlYTxZRB83dTDKfDahKy/s2tpjwoDRbZAbBVPcsI",
	"bHlgZhSbBvyEychQqbaqLraZ4bVtOyeObTHZPE/6Nla2/JTNabbKDM3sDIXwZevzagfn/8yVRSND0a1r",
	"M7jwp0H80XzF4re57tsktIOBPmWPWyfQGT5LV0GiOoyn9jKGUGta5LDxMKHAdQ9wg8hCU0H8RdAFz+4Z",
	"Igz3gtPbIEDfGfZT9VuHdzcJ3iGkK7hlIO4SpEA6kE8EeB+gw4aMu4d2zWIefPVMczR59gEbQVoEqNhY",
	"MIPVDBLxMpfeMwjf3Z1ux9RQyUTEbNMDLqGw+WFXLXZ3f8jWwn+n98lyQbd/k2qW1LuHrnPsCIFXuiaS",
	"arYIJAqwYxgxCFoU7k6ltxekNn52669P9cn55PemvvMBxxgM42y22SyCs8FB1CwhGAL5rI8nsQxbWWED",
	"yQoWhq4BrDO7V6mZCW+1IygattIbCG23OqxUxmmlMQQPldWiOiXMSmkpDwlbLpn9Witi2cwbWctUeGsK",
	"Mq8eUiNdbFibVU/86PbbitidGL01Kg8uKQKtp4SBhYQmyZrwUtrwrsaSXjOw4EAMGr6RkFhO0AWrRIBx",
	"QSi5WbZZFDcLMy5O/NMrcsSNLLWb1HAuSNUgFVeVWm0Y14xBdpFOIDf5UUvhqiO/PFJxYeaurw37ZatL",
	"FsdlhFtREbX++oHV69WnpgKw1jOXCaBZi7axWRYK4t4wad10kqSLV+yaBYTpV+nCZtFsAVGQw0yvmZQ8",
	"Zi0h5jbbYrBO3D9d3qiUuFEsDBA0gZjJSqWrcEqpLE+Sc75iaVA1gR9gh6aheXJsqCiTeOQtMaAZi75n",
	"OlqC41wwOZf7gqZZl5TZVbHIWNSRmRtNjwPHzm1gSLVCRnj0SmGDsGJaNesGYLlFDPGHCgKblZYuZ8UU",
	"+h215OB7aAlRulpRq7bdZuZBKGB359U08ZYQFqiyVd+1Oz95bSlRkF95yQSTPDplWVoYmLtqK2YBqtLn",
	"WYlDO0faXLaozh5mKYSCrKHSsGaPoFABumIOK2VthrZtQvT5JdeBon8NiWLB9anZTjiHi3UTxXjyl1xX",
	"iQDBgOdN0hm7JMauujlfOJpfeqIGD7+ETr9IUA5VmFvCCAW85ym75l15bPCrWXTu6mr2rrdR07JYfGPW",
	"aVti5ulEDNJT1GpC9q9GoOBvTz408Q9penUYOQeR0gejVkVh3lneDAQxV/52xXQgi+8lI+wDi3KNSXQG",
	"cU9mbZ0clG6lPn/0FMPkgXpQzTD8YPWgmmGYipg8WD749CzDH0PZzIe5/ZfYcZqLycf34OdS/TGQ9vf6",
	"Jyo/hWl7UVZGJtdUcgghvmLrPbS2ZpRLKIjyb1SNudTVuTAwDjJ1Mhetjpbm/athqF9thYo1oXKRr0Da",
	"yRW8YpqKmMoYa1wStRaafjDIw4vCyHjuiqxs5EHx0pKMZ6DPWwBbNjUYxeF6r7GYrlsEyUXMJKHkkqol",
	"2YvQd/FDmD+8SeXVc97iemY+Ylp6l2AetwsppDFrey6Es13bhQ4gdbloJSnltT3YBNeKbidUL99mvU5b",
	"lT4vPhihFIvC9q7La9x0zBCEFZ894sYM/kEZmJRomTNzdIXoFKZ5Nm89i4OnFtpy4z6lLZ6fRWT/Q/WI",
	"ADeZMEWoBq9XlqQ36NAIr7DZgqKaK+uOCb8WSx/uLVFxKAwQ5HZugFr3uoItQB9fAmrLAi0LUIN0H2G4",
	"0CeCOVQbYWqgGsQRrbNSwN2gGndT+v3h/PwECwYZShBQPdBZJANvF+ZYJ85jWaapJkeHQfzJqFI3qYzb",
	"GDD8SmxKFrRQBtZV2GyL8UIyzhXP0GHlJyaLyheBdD1XPLOMrmUaybXXISxN6kQNAsb5qzNMI+X8pAct",
	"3Yx+xdbDR79i6+GDp1dtZU3h026gnysm23lE97V3rgFOw+UN6JYmllpnA8UJgSsZJlAYqnASJCPmVydC",
	"oEz+QCERsVKlTr0kyc7Tv14SFpaimMHLkr+7kVxrJj5ZHJFNccRJE1TZjE4iIh2CCpbQDm1eFlEL705f",
	"IamM0pUh+XNt04JfUgVfZ+RYk4gKy8Yw8mvOoKyMpCumwU0wj5aEqgNyMdk3FHFfp/vO3ewf0Po7aN3m",
	"a94q8hTHd/dSjsPINrq+pS5gWXkSOrmRsqWXPmEnOgTAWjj3lEQ0Scy7GSWpQCk1iEmQfwMrO7XglBkP",
	"8Q1ZwVQkWITQdTXsL/pqWTm+POoZeafAdxHyrxkEd5iJDDDISfB22VU7fvNy7Q7YenkScxaGqYaVMGX5",
	"aMhDtmRJhrRMY4Iyu6OinK7WWeEmuZEeZeqfawhjjld04ae2qVPDYeEK3gA/pUm+YpVhmjWuQDcaMLf6",
	"9NRRN0+bWnJFXi31jEZXg8pF4aTBTO1hsDzLeRKqVVB8q4Y7lIs1ohYUssJVX0Lbhrb5flyo7yls4G4d",
	"7Msj2szL3uu3W1f7cmBUYvPfaKs5zv/eKEEBb1+LNSlKMwlKvHYV+dHbk9OSvHHMTcsEvUzYZrpx7PMi",
	"Y8HCIqDKeHHy4lV1rocsY8meZAkzuzC3BH4Q7IN2vz4Kc8443Ukar6honRA/+7lAmwOB+NgOH5QuDdDj",
	"2IG8gPYg4bE8aSNGhqVHIFgdq3AtzAq4UJomyYaWCxi0YwbbAPytcuF0Sx652mK/ZzBmcDlq+SNbdyzn",
	"7OwHkuWXCY+KUng0jrex1sTvBO/cOLayKsrdHPRZOXNoYZA+tH1F8BkYHogv3GJ+w6IEk3p3kCFAzkBq",
	"QxA0WsAyMEr5aGDwcUu4LyQvwUjf0nbcNkY4bBfijMsYV/BjwWBclEJdLO3F5PE3X399MYF//V9/+9vF",
	"5FGLAiIkqD1nSnPhmBC97F9tOGwWNwxJbHtGCOt42sM1/QMPx3lVv1eDvSp8jher9MfhW4p7suGFuadI",
	"qD9WzFCDcIcSncJf3a/EdlQBP21w20AtcrNkknn9izTOmBRwx1cm7AdY/V5BbFv+w/PzEt4tagLLMHPH",
	"q9YIIuD16iKQkTHhTrZKxMWop2zBlZbrI8lig6u0P2Pys66+Zuw01dGLD2D0aX/SoJUvAUHkHLCaH5yO",
	"btCVfVZOF7qzBWzcagc4qlU7lHqMYqx58GV8a2u5OCeTSnOnhQulW0hFmWx8wQSTVLeYSaKGZDCMmtUk",
	"CogJsK5WwxQ6Qcc3cH5Sy/PUh23hgqVl3uWBZXqiuJLzRIdwGNUsOHKIU6/d2/Km9FzZFq/OeovKtU0v",
	"QUu7wb01aGmvyVx16DEKjVJx8o27oTa7DG7W8HUA+z5PxTkPaiD5ypb+cUcTl1E1wyvrDXEmLds4gr+N",
	"bNHpFVEgVQGSfn1SEB3D1ZnSRWB7yA2Zb6XbzL/TS5KlsSIPy7LT4LSHIRbgGOYil2D7WCVguGDTmif9",
	"h2qWdNuOcKyliT59EHbheSxbF3mSLakK7xy+tLgR+J1bDtZFRpwwEWNeFQAa/vMkV0v810u8EFws4PjU",
	"ZDqpJD128Y1HVEQsaYuPUZpKPRzZFcaCDEX1bgnKl/pCrJMnaPbp/gYzTf6YrVIG6kriDVxml+iy41mK",
	"7Bjkcu0caMPqlLCp441n5vDXPNjGMYw/excUpw5RlKJRlOZCl4J1jys2CJwdPA1+L+uNFLBKUihPs9md",
	"DsPtnTVwbmgF/4GqJYurhnC3zrD1bcmSJCTQoqs0uvv0j7KpVqc+4lBwhXCkFTNO8iQpo2vKCv3H8zep",
	"PkFRrFGr33F31TxUD/w+D2bkn4aaKAY49eAwuaFr9WDq0UCuwA2cxYRdM7kGX7harzfmS6UT+IHQxFDx",
	"NWEfAHSi5r3vaCrOOZnWNwOjDkxpZeBTjGP+qI1lfrLjOZAGTDoHrRadXp4VR3P51wfaaCoraUsp+LxS",
	"csPK4sjNvT063oNnmFOhLeRTSajUfE6jgNtKVkGj3k15WAc7cjVjulmS/oVhVE/BKKPNcEXXhkbTBl9t",
	"OooUabqNm3x7dFwMBk54QK6oIvZVSuWqYFJNWxzIZYBvc11vmMbdfoMnJxIu7sHGCNOG3gen4PKtiE6C",
	"G8qaeqsp87R10y27oIEGSGg8xEOlf5+FUcM+hA36MtgrzlnThj1nu/J4aAVcKPX63UYaB1K/h/hUJmUq",
	"X7fx8WZ2aFGw8LZ4kNMuGlEil2G2IJV8wQVNinpsgzLuSgbKjzzEdL6pZFtBYqqpuirL8JvevKLFGJT3",
	"pAKF+sr7Trc1r/jdH3QzO/8tnHnmJvmjnP4NVe7gySWbp5LZKOsVlVfovpqVgLHi7yeiiLfQIfjyY37J",
	"pGCaqTMWSaa7CeeuiNZ0omC2oVFH5SoJdgxEVpstb+keSLXnHogTeIIdjNyigBwGkHLNwQFURqOOUeBz",
	"71Dhd6AcfupBqDcW3PYuDymEOhCCG7aRlQ9pzJXmInJxtlNrj2A0WhIOAX/KWhg1XoiLyRVbfwc2o4vJ",
	"7EIYDP9AV1nCzMJYGQDyXSbTOI9sDV7D76Xiu1ztMar03hPI88Tkd5c0umICyM1wUbOaCyC0O9OAuNQC",
	"1gYIv6E/ZXoN8Rk2m2tpCiSI28qIjOmcrKiOlhjJbNMr6mhZxh9gPNDhm+csnpEXq0yv90WeJLXZFXYj",
	"hou1hZVqN6M2ah/Ne11v/3E68Vb6SeXXVzQzG//9iq2ncMYfMWgnXD69iXLOpBcUoM0Xr4igM+nZIIe1",
	"0EumeVQeRxlQ4If1GMzF47imkqe5KlIWwDLUjByWZksjV0BEAnhIpljq6vfS+2pK3MI+hnVYXOSBq/8a",
	"xRWDP9wr2Gr+piThK15IvGXeNUDvwqkZo8SsXpPVKt0zCYwJpN4GCBVqWL/eK9SIpL/mrEj96Tw1dUq4",
	"UvABRSebc9JJRV56Soqx45CDgSskC5CxyLyK12iYFOyDdnelVAgX4D5CMIHPqXlbFFeg4YOxzLJshksb",
	"TMscyOxOq87lZt8uesRwEikYR6kRGefsxsXY4ZlmVClz9eylhRN3xnn0ZS1cyEFriiFgsE93tLXSuTzG",
	"Ct2Jg5SFtM0ZwqXSLs8+m5JcJEwpsk5zXI9kEeMFKG0MAdSyFlXGqMVbfUW54GJxrNmqhZOpp0e8VOZg",
	"jZQNyGXXCYDHB9MQKAN+605ukze4g3ZbASNf0dMhixPFY0vQIKE6hMg5ygZKnzqeF/twi1IkF1civRGA",
	"pwhIM4wDesLmmuQCLo+ISbri2gsOVExymlhTYHWhXgY18tBmY79kEc0VIxw+Q5aRZS4giC4tvwIIbF3q",
	"hCrb6FG5H8ks6BAD63vCjRQxg1vtxOWQTZMYFNZUkOsnsyd/I3GKBlemvTkQyw3DKcwx5sqLXKjjjdnZ",
	"X5nSfAXWiL/ibeO/2TwtLqjfLAJLshfJh828kgGlbBsbHcKBGsgi+NLqm4akkGy8GbXnrMnUBgOAzuHk",
	"DFpesbVPPe2TD4oQUBGEhQyIhWurxF0E6JW+qkBA4JWtFUc8NtzNm1TDf198MI/TZDp5njL1JtXwd1CU",
	"wozMLfuyvBm2MWtYuSSdW+qXDQi9Tb9vgl11MYnIwJSRlcMNvPXDNawKF8fY9UmTs8O6uK5u1utUcJ0G",
	"lGp10QKa9YvHfmSP7dTPqfujvw8FZA+pAObvBEKxPQfwpmNG8c3c5CqbRJPEyKTwxsZhVgkpv6X4CnrY",
	"t9o6ZkLb0jWz5vwmRKpLf40tOcmyMZAKG8HVdGMuyUBki0KfGxFd01VL7CwE46OHA/iiGRHeFsUYbu6P",
	"WelTsMlclszHbEP3AusqwVtKb8MbHhVvaMUTjxaKa1KO4kh/xTlrRk7SLE/QI2PtGSpn5JTReM9wwAOz",
	"CSefKki8RjHCOhiCpQwZdiRoEAFHhc+vpnJBhXmiTDvDEi9Saf58qKI0w1+Rtj8qGM/J1nFqHf6XUOUl",
	"dEqeJyTVJL2B5BlYdgl+NyKKEY65iPfNXBcTKze3MHsVdjUYyW6Ze78CO/Knc+7sQcBCPFBeLQDL/vb4",
	"mYbeYaQ6p+12nsO61sfP21J7sscc/LvLwT8Mp4uziTuPvcIVoGttq/H5Ld7JgnCNBTLGUjdjqZt9/1oE",
	"83l2+q/3XbSwwrbeohrW4H8dS9ncfymbxnkMkpUq5HYsbPOlFrZpkI/Oy24DMpzO3Fw272sg/SpXWULX",
	"4ez54F1LCu9aYB/UMr1xifNkGFbsA17P4wD6vbDfyPHzgruuLXAA73lCdbQ8RfypBD9tkO2hN9sSePFj",
	"uiFfgUNjLKeYJWiGw8KKkGK8RXcTjuY5JP/n7O0bcpICNYPwubbsDnkLP4dX14YqpiAJmkXNGsiXZl0p",
	"CeuEo6usT/nN6UMtGbFhhRU64tX9wVbBDQ4oXH43Dg4dCwnnzt8uXwxIZjdUFZRus0z23qyhwzxlCdX8",
	"uiWzzqmfrUHapmg7dwg4JOvnYaCv0wE7JcKbVFvhlwrr1gl4Yto7zUh6zaSXkacwDE+UjPa5iNmH2b/V",
	"MJJQSbAS2nfx1SGuw5FauhMPIRZc2/QhwfM/7Tj/SrpSD+YvufZxAdwVMeeLn9xk5MdGyWmUnPbLS7RZ",
	"DhOv325zmJQDh8Wu6veq0HXqpQEZ7/i9y1yydhyDRC6P4o8C15cqcNWoTsclrwtbNd+UKlMxLDduPZt9",
	"b15cP91dX+MztSzb9my9JYq43mKzAjFViHxigZbqYJ8aTbtZoRRnpz1MmNSnOYbL10UUbwdNBnpZjVyt",
	"1VKCDG9m7HBJybzNOvjc4Z7jcfkKuWzPIZZeM2lEslxZKa4I/rY+zTCxkdbI93CeB91p0PsTnHclN7+4",
	"iP+zLZ/5dJL1VJitVpbFHaFzh+SLBWQVCkASDafotnzNJNf9Zaj88z6znTCXY704kxvRO6bKPqq2z17k",
	"qkzWzMFrvzZwxokw/6RSYCDckeTgqjaZTqB+ybBYuda1lAO3NvFmbG2DS/E2/WPwET0t3kVIo8E+GOE9",
	"JtecwrYPT479TR8Z/IXYLXbGF2aZTlc0nZR1dcrfsOLSxJbFmlQku3JlZ2sRTaaT89byf75kWHHjsIq2",
	"Uv2AbrxZZpof/D45OnnXSrGyPOQTMp085+qqtYIUV1fhXugv0+p90+pN87Gg1lZVWHFz+Tj0dWvZTd+7",
	"1bWunlpaLZAwr1+r007zAMOMwJkfIogUD5ujI0a7uZu6VyPkRWWeI3gtE+DLTasZeevckfHXDJyH7dXn",
	"yhW82ICPrT9foWxydJUlXCzaqygVr80l0zeMCbd/Al3Nuu/gASlKY3RUxWg76ql/FIEdd1FnIAethMp8",
	"rWp+Ks4Q4Flu3ZUxNtFGuZZawhQzSINztSV+IP3x0Wo3aolGLVGTmJkrt6meyOu5a01ROXR/zXKMYOgN",
	"R8Rm4L4FsVLOc48rUqE7iAGzoK+eOWiuf6BqGc6i4ThJdHOHxndX1j4ItfbQ0l6AQSsFZR9yQ302B1iX",
	"JcYD5bRyhJXl9WGH0ySO1Pye9YG281pEG/NRwAuMGsEvVyNYe2E62b6aVtAls32oHhVMHUZ5darDesot",
	"Yn3kRl0lLhrVG45Ny6IF5t0pO5TXXlMuMOwxxG9ibQaRGtRxvbm50y9otLTB19WhbOVZO4BZsM/0dt/V",
	"u63EMqRkpHOdL0pHNiF9WxUjA1xKN/5toZj1+3+iapZuR0o7Ex06DeURvLht0V0Fw0KWVC1LPwuzjpZ4",
	"fzfwy46Ii2JwL6AiMPaQYLYtNMz35AlTmTzIgQl28zYc/AA3lN0QiI0gD3mRZugyweIGIk8gJtglUW2q",
	"fc01S3PVMYFr8gmz2GfueyjO3FUQAYs3w5EzWTyPJQkoaUuB6g6SGB9ShMhYiQH/M3PRh+7vQMn+gQF7",
	"Fb60uq8gcmGReNR7YmKEsDmheMWW6Q28XtC2qNJvsMkWpze779JxPqM6Wp7Z0KX23Mt+o6bSUWlJNVus",
	"h2scayN2AMPPmFchrf5nZ1exmyYZ/ury/CcslMrEZuDDy+TV0e5UXOZl7cW4eUydTGn4cD/C+cgc9vUs",
	"jxesfxH19lC2DOpEnS8lU8sUiwN1jeE5E4b9tnC1Z+5kg5fdnTsKwSmPML+sq9fu9mhuZPVkfKJWRYXQ",
	"FTtTyx2VhDw7+6GrImQm+TXV7Ee2PqFKZUvZmm82K76jilQtT4q+f4yKjpUl9VZetDsHAA0vvhhCHN+Y",
	"vZnnr/KPucdefktV3sz2a66AruZbV623ripn5a5CRK6NcbTMIkcNtc6lsNIolPOnSWIfvjgVD1yJRYJJ",
	"Qry4ylF3cbu6iyhY4+UsXywYxHWDA6k9HNPW5pnlLtfNlDwmfO7SRNS51a+eBjWFo/Jip8qLlix4QzxB",
	"SkkN4egiFFpkZ6rCLicrGi25YK1T3SzXtQnMQVsu9wISkueSXUzsemxyFa7K/EJslem1zYcC6VSqomeZ",
	"leiQnMIySZRQiQHKzg/abhbQ+DI3lIdhYpb0mknJY0ZaNNKqm8S5aJMCeOQtpHc6IBeTM2RqLiYklf5O",
	"bx1tDNu/R0W8Z0HaS/JDOiy7cUsmCgwokS70IJyfvC4fwdoDdfK65slWFGVyZTIIXbCgq3quly82Tb5u",
	"5jMdMZeSwzubfz3MdCDn15Ee0BJ8M3SZ5PXT88Sb8WzF/941Kp1KumDfd5c51ikOio07yl41T7DmiNI8",
	"x2qDqjnaj/wnTvAc3/LRqjxalaFH7fJsZliud96tbbk2ejgUIdCoGo9QazDy8fdvgwwdySDlef0pGE2R",
	"X6opMkSW+u5+I0yh8vZbJVo7CwBazbAaAz6Rm2WqygHcfZ9jTdd+lhbHH7LZgvYOK5dgNaDh2ggbhxts",
	"WCug055lsfpQdyQSqySxLoB7QxUao7zg4YGFnAYbn95Pe/BpCwNjsQGLezM4X75i/5O6yg2uTM2rFH3G",
	"A8WsfksFK5NaSWXdSGG248M3hy4K/fD0xeH+q7dHh+fHb9+4HNXmx2a5eg4J5lNJ0ohRgW+I61kUMTSN",
	"Myo1j/KESqK4OQmul9xaAqlkdApSkg1hJocrJnlE99+wm3/9dyqvpuRFbvBv/4RK7hx6c0FXl3yRp7ki",
	"X+1FSypppA3VdHvFjNFW4GAxeXgxefn6HKv1vjs/aivWi5aGs2jJ4jwJVokpX2xlW8Hqaa5Tc4wRidMb",
	"kaQUMigbkCC6KT+xsuYr9zV1pSE1WjcCvESvseFIpqKa+RFqlb2UNGLPvYCXoVYT7SFX59vp2jVodJgo",
	"eSxRdYvXbbzSS659khvObNhyUd2g7z9ikv1ccr02J7uydRgZlUwe5ihf4l/fO3rwf/55bvhIaG1kU/ha",
	"TgmB7VBBYRFK1WEo0bt34Twdlax2ngmUkNc0U7awj9+hzEs5c+W9uJkE8qu7pGIHZin/4p4BgGb8R7ae",
	"fDS7N0TGpdmmEeATW1GeTA4mmtHV/y6UEzOeliOaXWB1T0g8LdOEnDO6mljl/MSxD5XejQSFP1eHeP8w",
	"1O2R5aTwbK2FKkqoxEwJKyrogq1sMTt49YA4snjBCouqTXnMJblJ5ZW5gQqT5ic8YgKtRHZnhxmNlow8",
	"nT1ubObm5mZG4fMslYt921ftvzo+evHm7MXe09nj2VKvErwnGlIu1IB0eHI8mZY4Pbl+QpNsSZ/YbLiC",
	"ZnxyMPlq9nj2xDqvAD4abmr/+sk+zfVyPyoUTIsQB/GS6brep1ElsFDXGQydGDy3WivIiQjZqGHep48f",
	"18oIeqWN9v9tNaJ453sLG5WzAOLVsu38aEDw9ZNvdzZfIR42E+zn4HRVVk9kULj766d/v4PJz9OUvKZi",
	"TWygFAqwmi4gMKx6cEifKod/TRNu3ozW4//JNjCkooYGkAs9fPyuFyCdpCummVTACjapV2hUQ5vc0goq",
	"tGQ0Bsrorlaul6l0ubWmHijr1Pr9LeJh19GYncA2AB/uZNJnNHaogJM+ubOdclHu9U958aaTv93JGbsa",
	"T1aUJy+kTOXgex+VcZcK4y6dVN9KBED10RqvWXUTrRID07O1o+ojD5Av1zKtRUNDG7Dgi/NRhTqYhf4C",
	"fSL8mhqWNYIRzACQKhvTn+t6oweuiMQDWwbAWtYKT7ZqjYUWDqkoMtJFlaahrNE20z0GlGnJI12WRgAH",
	"eFv7wiX/xqTQXNpSP9XCoFDesyhQE1poUim6c3erRXe9qZOaoJKDTWRvQHzFyIPvHkzJg+/M/xp268Ff",
	"vntAHrLZYjbFakVPsFzRk+kVWz/9C/7x1MpaoZ3CjNvt1GDSin7gq3xVKYmBiFds0i/UURbhOC+LokBC",
	"LawA0Y5ole6Ez6tYDhm6cNBatZMVXWOhi0tWlvWHYmfFxYHoRa++CECoFTP4ChJrlXDq9Ua41Xe2lYqA",
	"Zr2dBfxyX913gloOyL57j7+6g1m/T+Ulj2Mm7v2pvYvdnlkx8Z0o/CIqD23rYwoB6lkaMvocYXVTOuBF",
	"bT6o2Lkrd4JdwLM0Xt/+5UOYlboQLXP2sUEFntzVQkKAjkcycOtk4PFdkAEj7Scc9Xsj4ekgPIOY/f3f",
	"zUP/EclTwnRAA42/VwkVsdeOlASnSqCeQ6cuAtWrEfADx/pppOE+caUFKwNRWgUnY+tqVonUH09d4PiV",
	"Pw3N+PoOpnyTavJ9mot4JBq93EpQ9JeMYnm/UqaIOu52lRa8ZPqOCcECHac/nQpMJ7ngv+bMVjUDvuZ+",
	"5JuRVoy04o8n2VAdhZ1lo+WWkg30vWNykRUlGHfFNgyVvfZg6v/c7DQrFRUGSV73TJ9GoevLIoqjnPcH",
	"I8N5kGWDAiM1ru1oMNd2iv3vmBSX2Z3unBbfmR7sXqnxqIYbX4TxRRg1f07zt0+zTKY2ZWzwITmEBpi8",
	"iol1F1/fZOfRvbW1w6GbfGePCVZ19xc8PiYjaz8S8pGQf96EHJ2OKeTOUfuSqRyrQIaNy6fwvfBUvqSK",
	"xSQV6B5UeuxQEe+n1g2n+HUWEAXMaBiio27Jtoyj40z3RACrS8BJRto3upTcC1mo3PfJ++nkw568pJg+",
	"yaYWs6Fp6F4PEjRYa+GWOgrxsUlDehw88Rb0eXOWxGB03RxdN0fXzS/EdTOAIzZLCpkndGHwBIMKGaYf",
	"NqtZrahcVyNv1Yz80+wEQJUSkKxc8BmCBSBZyWQMN98O5sWo2vBLADgk6HyA2FTB+wcljOphmDdmHQ/s",
	"wGaoB5AXUuatV99rG8KyImvMrdqBkb6OTq0jB3LPHMgQD9Yay9DmrlqU7ro9+eGuHVH9WUd19+h1+iej",
	"DE3ZYoA/6XPnT9pLNrBlQTY20hDXBh/dQ0cV6Ojytem7354KoP/yvmR6Zzd3Z/6cd8G0j9d2vLb3zK53",
	"u2X2Xl1ouLPLO3pX7pCAjJLEaG8dhZdd0cmQuwt6rAwhk9ZDcmeE8rPwfdxEz3J3hHHU6YyUeKTEX5wa",
	"aT9mUCVQFVkcQxS7SItZGqBQ3eP1baqWyo87VDCVg34WZNyHwsjrjhR2lNDvmd4lVGnFmOjMw1mUfDct",
	"IY2v0nSVtRCmDs3cK6r0mZltJxq61nXN0afw89DeFTDp4DW/DtSxTyEbq1nESEZGMnLPZEQyETOJxZI6",
	"yYhr6GXMb9CKU9tml9r80OTO6Skq6ljtimpMW8tEX4n0RhQL+cnluw87BkHj02rbyR/V1jBSqVGcHOli",
	"jS6WFaE6qaJfDGM4N3XmSvuN1s7R2jkyQX8Ma+fG19mzfe7sQo8W0FErNFKykZJ9ij1yY0JWsU7ujJSN",
	"NsqRdI2ka5Tx/kAyHhMyTZIVE3pADauycSXILCTVvSiaFmWsBlNPOjDdFYbBQjk/QbhSeTWxKpTtz2R6",
	"zWMWT/1qdDaAbsmiK8L7cqLYODsVngTi6SB2kSsSUcWKED/u9HQ2PrIOEaj0SpOEpFBw3fSd2uKxBZT9",
	"iTBMElZ+yQhbZbo1eDFS8t5Ua42DH0n6yI3+SQhseXODWUgan3uSCZRXaWCVqEaHMcXAmGJgTDEwVofa",
	"8OUeq0KNAfR/xLe0L5ZedDyZbXH1jR63FGLfnOeOo+1bFjA6aY+B9yN3HuTONwjH34zyYK8Q5dlIw9w+",
	"5RiwP8rsoxr2s+Js2rMFbEZbKrrXWyEsn4mHzSB+ZyQwo1LwfgSZziwDm1156HTLl370wrkdwjPKWCM7",
	"NbJTt0Bfu7ITbEZerS/QLRPYz8I3aEsl1r3Q1lF3NtL1ka7/+dR1W9RkCrwHzWfA9rqFZ+Czq7rU2EJR",
	"ieq+nwO3kH6V4kigRzXDSC63Cuv7dIXkdh71o1pypBcjvbg/teQnkYGwkvI2CMGoqhxVlSMFHEXaL0FV",
	"+Ukkt01xeRtEd1RfjszfyPx9KcLitZmnVSQ8ZVpyds0UoUUgAnaZXYhwYAoO2BeM8qeJdzhLpSapjJmE",
	"8EVb3A/iD8yGXPK/aqzJAzPGA/JQsBtDfedcKt26OBi8sqgYh4IqpyqaTCdM5CuDDBT+gh/fT7eN1cDz",
	"x3MzR+SCLfrieHZTZ/GLjmK6VW2EObYxzmOM87i/p8hgYPX5mSeM9cVGfm/a9MVDfo8DjTGQYwzkGAP5",
	"5ZZZPrYZF9rqKbtNA11pWwmNbY5WdYaD3F/5YiBb46M8Psr39ijDTRlSvLj6DLfFWEKrW4qrxLHvOJbS",
	"m3T0ARvjJ/9cRKHBqe//Dv/9uK/ZKkuoNgyh4qloZ+GB/XCtSdE8xMOf21Y/lY161dbpjUDuybz6jWla",
	"lNRzj0htmRl9lCRGSWKUJMZsKobO1ujWyM6P7Pxn9HIPSH0Q29QHjQe2Jd1B7UJ88jt+e8943fI9cOYx",
	"p8JoXh7Ny1X1QZD7l4zGyPoW734vDXnJ9EhA7pKA1KE9UpKRkvyhOJfBuZl6lZTY0CkpN3KKqw49pl0a",
	"L/Z4sXfBIkDio96L+5LpHd3aHQYP/TnMkyPZGMnG/RomOxMo9ZIOaLcj4jEGHO2Odox60DHIaDTT7ohE",
	"duVA6qWQNnpoRzTys4gP2sCX5M5I4ui2MpLgkQR/WVqrvpwboCAvwz6rqnJHkMOi8HaxnbcqEI+y6CiL",
	"/oll0Xrt2eGS6a7u8iifjvLpSMRGIraFtChRCNyQGfFFx10RsVGAHHmgkXx8BpIOX9EFu8x5EveE8B6b",
	"hs9Mw7443rLlGMw7uuCPLvijC/4gslaSjdH7fvS+v7c3snwQB5UwDTyLbXG1ZdNbCq71JrjjCNv6zKO9",
	"Ygyz/ROSizBfvVFh0kH0BJtX6MlG8npgktEZdpSiRyl6Gw6hqxTooNv8kumdX+XPxCDYzTeMd3m8y3fM",
	"7ffU+Rx0n6H1zm/0aBbcMVUZBZHRcWqUfXZJPLuLeA6indYWuXPq+VnYIzfV39wtxRz1RSOZHsn0F62i",
	"6vN0Pe3ydK3Q7A4JdzsXk1HOHanOKOfeiZzbqGK0jdS701s+yr6j7DuSt5G8fZIketrjHNvBvzSk0p1S",
	"t1E2HXmnkbh8fvITOmQOqrsWc6W5iHThOIl9i3JiJRUqCcM6Y20F2l7hzAPIjxnF+jIW9EbahRWLkOmq",
	"zUnwiou4k/y4smSY7mZQSbJDMueJ9fOtryUVyRo9fQsnY6KX1PfmXfBrJrB94aB6K96vO1glOn72rXLn",
	"nqsluuF676TO23byM/tAV1mCPXC1L/AXuNk2edLBxP5Y+s2am5O4awAOslgp8ZrLVKyY0N9lMo3zSGPu",
	"SckWPBXf5WqPUaX3npgNcCa/u6TRFRP2Yg8jJHD5RhfV0UX13h4kwPvqW5TKBRX8N1jHZqVAKz1nhLw1",
	"tA2phap+RBJnyEeumCRLqgiNIqYMfQlHgrytrOoWeUR/ovFqjlfzzq9m+VJBsFRaQ3x3c/3fqxdYsixV",
	"XKeSs55ArFPXct0XiHXqjzlGYo2RWGMk1hiJNYD8lRRmfEvHt/Te2NziSVwPqW0YeBbbArHKprcUiOVN",
	"cMeBWPWZR8eaMRDrT0gtWhjrTcoQDKIn2LpCTzayCAUmGQOxRsPMaJjZhkHoKE0w6DK/ZHrnN/kz8U/r",
	"ZhvGqzxe5Tvm9bvLBQy6ztYLa8cXenRF2zFRGcWQ0b9/lHx2STs76wgMIp3W323nxPOz8HTbVHlztwRz",
	"VBaNVHqk0l+UfsracNci6rX8YtOztYj6bb9l29H4Oxp/R+PvaPwdyBSUhGM0/47m33t8MMuHcZgBOPA6",
	"tpuAy8a3ZgT2prhzM3B97pG3Hw3Bf0q60cZqb2YLHkRanDW4Qlo21JsEJhotwqNYP5qRtuMZOm3Cgy41",
	"WIVv4UZ/Npbhbk5ivNTjpb5zQaDPOjzoYlvT6C1c7dFGvHPyMsooo/1hFIt2S0V77MSDiGhhKb4FMvqZ",
	"WIs31fLcNfEc9UojzR5p9helymJScVxBq3yr7NC2bVCu/cmOc4skyk3RwdqNlpW7RiuHP++hLxpN8aXO",
	"ZTI5mOxPzGtpW9eR663DIsxeZCghE9puYVY+0NUPk6a11xsoFeSISc3npjU74wvBxcLCrero4Oz+ZWuF",
	"rWXxCHTPg3mKgoPGmMKocwSzZWxHaIQpM+oD2N97V/JCyDRJVkzorp2yotWgHZr12WxFXCwIuzYo4w9n",
	"fuhdWrWes98fK8j29W+rFWsH8RJqbbIZm8yIRjJVisR8PmeSifA6MUXKJqP7KUSCQ1ZyN/RBoC1Jgx3L",
	"cwbqH6nN6acYy3skBuw4Yhw2HHgh7IiOPnx8//H/DwAA//9GG7KwccACAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
